contact_links:
  - name: Question
    url: https://github.com/ejh243/BrainFANS/discussions/categories/q-a
    about: If you have any questions, head over to the discussions page to ask members of the community