dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.9.24
  - dill=0.3.6
  - htslib=1.16
  - keyutils=1.6.1
  - krb5=1.19.3
  - ld_impl_linux-64=2.39
  - libcurl=7.87.0
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libuuid=2.32.1 
  - libzlib=1.2.13
  - multiprocess=0.70.14
  - ncurses=6.4 
  - openssl=1.1.1s
  - pip=22.3.1
  - python=3.7.12
  - python_abi=3.7
  - readline=8.1.2
  - samstats=0.2.2
  - samtools=1.16.1
  - setuptools=65.5.1
  - sqlite=3.40.0
  - tk=8.6.12
  - tzdata=2022f
  - wheel=0.38.4
  - xz=5.2.6
  - zlib=1.2.13