/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // These provide the sidebars for the user and developer information tabs
  userSidebar: [{type: 'autogenerated', dirName: 'User-information'}],
  developerSidebar: [{type: 'autogenerated', dirName: 'Developer-information'}],

  // You can also create a sidebar manually
  /*
  xxxSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'label',
      items: ['path/to/file/'],
    },
  ],
   */
};

export default sidebars;
